apiVersion: v1
kind: ConfigMap
metadata:
  name: setup-script
  namespace: kube-system
data:
  setup.sh: |
    grep "LimitNOFILE=infinity" /usr/lib/systemd/system/containerd.service 
    if [ $? -ne 0 ]; then
      sed -i '/^LimitCORE/a\LimitNOFILE=infinity' /usr/lib/systemd/system/containerd.service && systemctl daemon-reload && systemctl restart containerd
      echo "Patching $HOSTNAME"
    fi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: fix-open-file-count 
  labels:
    k8s-app: fix-open-file-count 
spec:
  selector:
    matchLabels:
      k8s-app: fix-open-file-count 
  template:
    metadata:
      labels:
        k8s-app: fix-open-file-count 
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
      - name: init-node
        command: ["nsenter"]
        args: ["--mount=/proc/1/ns/mnt", "--", "sh", "-c", "$(SETUP_SCRIPT)"]
        image: debian
        env:
        - name: SETUP_SCRIPT
          valueFrom:
            configMapKeyRef:
              name: setup-script
              key: setup.sh
        securityContext:
          privileged: true
      containers:
      - name: wait
        image: k8s.gcr.io/pause:3.1

